openapi: 3.0.1
info:
  title: PI Navarro-Piñero API
  description: Descripcion de la API
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: /api
tags:
  - name: api
    description: Raíz de la API
  - name: login
    description: Autenticación de usuario
  - name: roles
    description: Roles de usuario
  - name: users
    description: Usuarios de la aplicacion
  - name: weaponry
    description: Todas las herramientas disponibles para utilizar.
paths:
  /api:
    get:
      tags:
        - api
      summary: Conocer modulos del sistema
      description: >-
        Muestra todos los módulos disponibles con su descripción, guía de uso y
        endpoints.
      responses:
        '200':
          description: successfull operation
          content:
            application/json:
              examples:
                Response:
                  value: |-
                    {
                      "description": "Esta es la API disponible para el proyecto",
                      "userLogin": [
                        {
                          "description": "Autenticación de usuario para uso de la aplicación."
                        },
                        {
                          "type": "Basic access authentication."
                        },
                        {
                          "endpoints": [
                            "/api/login"
                          ]
                        }
                      ],
                      "applicationQueries": [
                        {
                          "description": "Realizar consultas sobre la configuración y estado actual de la aplicacion."
                        },
                        {
                          "endpoints": [
                            {
                              "/api/roles": "Administración de roles de usuario."
                            },
                            {
                              "/api/users": "Administración de usuarios habilitados."
                            },
                            {
                              "/api/weaponry": "Administración de módulos para acciones ofensivas."
                            }
                          ]
                        }
                      ]
                    }
  /login:
    post:
      tags:
        - login
      summary: Autenticar usuario
      description: Autentica las credenciales del usuario empleando Basic Authentication.
      responses:
        '200':
          description: successfull operation
        '401':
          description: unauthorized
  /roles:
    get:
      tags:
        - roles
      summary: Obtener roles.
      description: Devuelve una lista con los roles existentes.
      operationId: getRoles
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
              examples:
                Roles:
                  value: |-
                    {
                      "roles": {
                          "0": "ROLE_USER",
                          "1": "ROLE_ADMIN"
                        }
                    }
        '401':
          description: unauthorized
  '/roles/{roleId}':
    get:
      tags:
        - roles
      summary: Obtener detalles del rol
      description: Retorna los detalles del rol especificado.
      operationId: getRole
      parameters:
        - name: roleId
          in: path
          description: ID del rol
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
              examples:
                '0':
                  value: |-
                    {
                      "role": "ROLE_USER",
                      "description": "El usuario que porta este rol no puede efectuar cambios en la aplicación ni acceder a la lectura de información sensible. Este rol esta destinado a aquellos usuarios que deben realizar operativos y campañas de ataque unicamente."
                    }
                '1':
                  value: |-
                    {
                      "role": "ROLE_ADMIN",
                      "description": "El usuario que porta este rol esta limitado a efectuar cambios y modificaciones a la aplicación unicamente."
                    }
        '401':
          description: unauthorized
        '404':
          description: role not found
        '500':
          description: unexpected error
  /users:
    get:
      tags:
        - users
      summary: Obtener usuarios
      description: Lista todos los usuarios registrados.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              examples:
                '-':
                  value: |-
                    {
                      "users": {
                        "0": "USERNAME1",
                        "1": "USERNAME2",
                        "2": "USERNAME3"
                      }
                    }
        '401':
          description: unauthorized
    post:
      tags:
        - users
      summary: Crear usuario
      description: Crear usuario nuevo por parte del Administrador.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '409':
          description: user already exists
        '500':
          description: unexpected error
  '/users/{userId}':
    get:
      tags:
        - users
      summary: Obtener usuario por ID
      operationId: getUserId
      parameters:
        - name: userId
          in: path
          description: El usuario a obtener
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: unauthorized
        '404':
          description: user not found
        '500':
          description: unexpected error
    put:
      tags:
        - users
      summary: Modificar usuario
      description: Modificar los datos del usuario
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: ID del usuario a actualizar
          required: true
          schema:
            type: string
      requestBody:
        description: Updated user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: user not found
        '500':
          description: unexpected error
    delete:
      tags:
        - users
      summary: Eliminar usuario
      description: Solo se puede realizar por un Administrador
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: ID del usuario a eliminar
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: user not found
        '500':
          description: unexpected error
  /weaponry:
    get:
      tags:
        - weaponry
      summary: Obtener herramientas.
      description: >-
        Lista las herramientas ofensivas disponibles con su modo de uso y sus
        endpoints.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              examples:
                '-':
                  value: |-
                    {
                      "0": "Pandora",
                      "1": "Mail Client",
                      "2": "Bit Mouse",
                      "3": "Crozono"
                    }
        '401':
          description: unauthorized
  '/weaponry/{weaponId}':
    get:
      tags:
        - weaponry
      summary: Detalles de la herramienta.
      description: Obtener detalles mas especificos de la herramienta.
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              examples:
                '0':
                  value: |-
                    {
                      "id": "0",
                      "name": "Pandora",
                      "description": "Dispositivo semi-autónomo que realiza ataques a redes inalámbricas. Se utiliza para penetrar dichas redes y recolectar información sobre los dispositivos conectados.",
                      "configuration": true
                    }
                '1':
                  value: |-
                    {
                      "id": "1",
                      "name": "Mail Client",
                      "description": "Permite a los usuarios enviar un correo electrónico utilizando el servidor SMTP deseado.",
                      "configuration": false,
                      "body": {
                        "smtp.port": "587",
                        "smtp.host": "smtp.office365.com",
                        "smtp.encryption": "STARTTLS"
                      }
                    }
        '401':
          description: unauthorized
  '/weaponry/{weaponId}/enable':
    put:
      tags:
        - weaponry
      summary: Habilitar un módulo de ataque.
      operationId: enableWeapon
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
  '/weaponry/{weaponId}/disable':
    put:
      tags:
        - weaponry
      summary: Deshabilitar un módulo de ataque.
      operationId: disableWeapon
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
  '/weaponry/{weaponId}/configuration':
    get:
      tags:
        - weaponry
      summary: Obtener archivo de configuración.
      description: >-
        Si la herramienta lo posee, retorna el archivo de configuracion
        necesario para su uso.
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta.
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
    put:
      tags:
        - weaponry
      summary: Establecer configuración.
      description: 'Si la herramienta lo posee, establece la configuracion provista'
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
  '/weaponry/{weaponId}/actions':
    get:
      tags:
        - weaponry
      summary: Consultar acciones disponibles de la herramienta.
      description: Listar acciones realizables con la herramienta
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              examples:
                '0':
                  value: |-
                    {
                      "id": "0",
                      "name": "Pandora",
                      "actions": [
                        {
                        "id": 0,
                        "name": "Discovery",
                        "description": "Escanea access points (AP) cercanos. Almacena los resultados en el archivo logs/airodump con un período por defecto de 20 segundos (parametrizable)."
                        },
                        {
                        "id": 1,
                        "name": "Stop Discovery",
                        "description": "Detiene la ejecución de la accion Discovery."
                        },
                        {
                        "id": 2,
                        "name": "Fuerza Bruta",
                        "description": "Obtiene contraseña del AP mediante un ataque de fuerza bruta (Pixie dust -> Fake Auth -> Handshake)."
                        },
                        {
                        "id": 3,
                        "name": "Evil Twin",
                        "description": "Crea un rogue AP (Honey Pot)."
                        },
                        {
                        "id": 4,
                        "name": "Evil Twin con Deauth",
                        "description": "Mismo que el anterior, pero desautentica el AP del objetivo para forzar su conexión al Evil Twin."
                        },
                        {
                        "id": 5,
                        "name": "Recollect",
                        "description": "Debe haberse logrado la conexión a la red. Intercepta tráfico mediante MITM."
                        },
                        {
                        "id": 6,
                        "name": "Deauth",
                        "description": "Ataque de desautenticación a un AP."
                        }
                      ]
                    }
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
  '/weaponry/{weaponId}/actions/{actionId}':
    put:
      tags:
        - weaponry
      summary: Hacer uso de la herramienta.
      description: Ejecutar una accion de la herramienta
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
        - name: actionId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
    get:
      tags:
        - weaponry
      summary: Resultado de la accion.
      description: >-
        Si lo hay, obtener resultado parcial de la accion ejecutada bajo este
        mismo endpoint.
      parameters:
        - name: weaponId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
        - name: actionId
          in: path
          description: ID de la herramienta
          required: true
          schema:
            maximum: 10
            minimum: 1
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              examples:
                '0':
                  value: |-
                    {
                      "weaponId": "0",
                      "weaponName": "Pandora",
                      "actionId": "0",
                      "actionName": "Discovery",
                      "outcome": "[Listado de APs encontrados luego del scan]"
                    }
        '401':
          description: unauthorized
        '404':
          description: resource not found
        '500':
          description: unexpected error
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
      xml:
        name: User
    Role:
      type: object
      properties:
        rolename:
          type: string
        permissions:
          type: string
      xml:
        name: Role
